import "./globals.css";
import { Inter } from "next/font/google";
import { StyledEngineProvider } from "@mui/material";
import ReduxProvider from "@/components/ReduxProvider";
import { SnackbarProvider } from "@/components/Snackbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <ReduxProvider>
            <SnackbarProvider>{children}</SnackbarProvider>
          </ReduxProvider>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
